---
azs:
- name: z1
  cloud_properties:
    datacenters:
    - clusters: [((vcenter_cluster)): { resource_pool: ((vcenter_rp))}]

networks:
- name: &cloud_network ((cluster_network))
  type: manual
  subnets:
  - range: ((cluster_internal_cidr))
    gateway: ((cluster_internal_gw))
    dns: [((dns_recursor_ip))]
    azs: [z1]
    cloud_properties:
      name: ((cluster_network_name))
    reserved: ((cluster_reserved_ips))
    static: []

vm_types:
- name: common
  cloud_properties:
    ram: 4096
    cpu: 1
    disk: 20480

- name: master
  cloud_properties:
    ram: 4096
    cpu: 1
    disk: 20480

- name: worker
  cloud_properties:
    ram: 4096
    cpu: 2
    disk: 30720

disk_types:
- name: 10240
  disk_size: 10240
- name: 5120
  disk_size: 5120

compilation:
  workers: 2
  network: *cloud_network
  az: z1
  reuse_compilation_vms: true
  vm_type: worker
