project_id: # GCP project ID
network: # GCP network
subnetwork: # GCP subnetwork
tags: # tags below are used if jumpbox and NAT were deployed using https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/docs/bosh/main.tf
  - "no-ip" # allow access to the Internet from BOSH director using NAT
  - internal # allow access to the instances in same network from BOSH
zone: # name of GCP zone
service_account_master: # service account to be set on Kubo Master VMs
service_account_worker: # service account to be set on Kubo Worker VMs

# gcp_service_key_master: # service key to be deployed to Kubo Master VMs. This is ignored if service_account_master is set
# gcp_service_key_worker: # service key to be deployed to Kubo Worker VMs. This is ignored if service_account_worker is set